spring:
  profiles:
    active: local
    include: auth

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

handlebars:
  suffix: .html
  enabled: true
