spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway
    username: root
    password: masterpw
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

account:
  name: localuser
  password: local
