spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: masterpw
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

account:
  name: testuser
  password: test
